### ISSUE TITLE
Not a valid JSON list

### ISSUE THREAD

**Issue by johndark** [softvar/json2html#18]
Hi,
I'v got an issue with json string like:

```
from json2html import *

aa = [
    {"aaa": 1},
    {"bbb": "ccc"}
]

html = json2html.convert(
    json=aa
)

print html
```

said: 

> Exception: Not a valid JSON list

but [online demo](http://json2html.varunmalhotra.xyz) can handle it w/o problem and it's valid json.

**Comment by sivasivacsc** [comment]
There are two steps to solve this issue
Step :1 Use Vi editor or emacs edit  /usr/local/lib/python3.5/dist-packages/json2html/jsonconv.py 
            go to the line : 137 for (k, v) in inputtedJson.iteritems(): change into 

> for (k, v) in     inputtedJson.items():

Step : 2 find  unicode and replace it with str

**Comment by muellermichel** [comment]
This is related to the following PR and should be resolved after merging:
https://github.com/softvar/json2html/pull/21

**Comment by softvar** [comment]
This is done after merging #21

**Comment by softvar** [comment]
Closing now
