### ISSUE TITLE
[json2html] Deployment failure- Trying to upgrade the package

### ISSUE THREAD

**Issue by hugho-ad** [softvar/json2html#23]
Impacted versions:
Master
Steps to reproduce:
When trying to upgrade the package:
Current behavior:
`IOError: [Errno 2] No such file or directory: 'README.md'`
Expected behavior:
Upgrade the json2html packages sucessfully
Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/10233975/21550255/df13b8ae-cdbd-11e6-9e4d-f502bf63c8d8.png)

**Comment by softvar** [comment]
Please try now, should work fine.
