### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by YAmikep** [softvar/json2html#3]
Hi,

That is a useful module. Thanks.
Do you plan to make it compatible with python3?

Michael

**Comment by softvar** [comment]
Hey,

Would love to see someone contributing to it, haven't done any projects in python3, so would be a long journey for me.
Currently, I'm not planning to do so, but might consider this in future when I dig deep into python3 compatibility.

**Comment by lilit14** [comment]
HI,
I hope you will make it compatible with python3 soon.
It is really useful module.
By now is there any way to overcome problems like "UserDict import error"?
I tried
 try:
    from UserDict import DictMixin
except ImportError:
    from collections import MutableMapping as DictMixin

but got 
iterkeys = DictMixin.iterkeys
AttributeError: type object 'MutableMapping' has no attribute 'iterkeys'

Thanks!

**Comment by softvar** [comment]
Latest stable version `1.0.0` is python3 compatible.

**Comment by randomInteger** [comment]
Note:  1.0.1 version is broken for python 3

Your __init__.py file has an error, it should read:

from .jsonconv import *

Fixing that allows the module to work for python 3.4.3 on my system.

**Comment by muellermichel** [comment]
The following pull request would fix this problem and keep python 3 support stable and tested: https://github.com/softvar/json2html/pull/21

**Comment by nitinsinghit** [comment]
I ran the script but cant find auto generated html. Please guide.
