### ISSUE TITLE
Boolean value

### ISSUE THREAD

**Issue by thBoo** [softvar/json2html#32]
I found this tool quite useful.

Only problem I have is it doesn't convert Boolean value, casting empty.
For example, I tried this json code in [JSON Editor Online](http://jsoneditoronline.org/) and it properly shows what I expected.
```
{
  "Example": {
    "HF": {
        "before": true,
        "after": false
    }
  }
}
```
However, when I used this tool, it doesn't show any Boolen value.

**Comment by muellermichel** [comment]
Both the following ways work for me: 

     >>> json2html.convert('{"Example":{"HF": {"before": true, "after": false}}}')
    u'<table border="1"><tr><th>Example</th><td><table border="1"><tr><th>HF</th><td><table border="1"><tr><th>before</th><td></td></tr><tr><th>after</th><td></td></tr></table></td></tr></table></td></tr></table>'

    >>> json2html.convert({"Example":{"HF": {"before": True, "after": False}}})
    u'<table border="1"><tr><th>Example</th><td><table border="1"><tr><th>HF</th><td><table border="1"><tr><th>after</th><td></td></tr><tr><th>before</th><td></td></tr></table></td></tr></table></td></tr></table>'

**Comment by thBoo** [comment]
It seems the problem exists in live demo version.
I installed the json2html v1.2.1 through pip. The converted html shows the Boolean value.

If the live demo version is fixed, it is quite handy.

**Comment by muellermichel** [comment]
@softvar : if you pull the following [PR](https://github.com/softvar/json2html/pull/31) it should be fixed. Once I get a free minute I'll make a test case out of my commands above, so I recommend leaving this issue open until that is done.

**Comment by softvar** [comment]
@thBoo Thanks for letting me know. The demo was using an older version of `json2html`. Now it's using json2html@1.2.1 which outputs correct result.

@muellermichel #31 is not related to this issue but I'll surely gonna review it.

**Comment by muellermichel** [comment]
I c. Strangely enough I was able to reproduce OP's issue in what I thought was the latest master. Maybe my master wasn't up to date locally.
