### ISSUE TITLE
Drop support for Python 2.6?

### ISSUE THREAD

**Issue by DeepSpace2** [softvar/json2html#42]
The last Python 2.6 Travis build has failed (which came from #41):

```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-2.6.tar.bz2
0.13s$ curl -sSf -o python-2.6.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found
Unable to download 2.6 archive. The archive may not exist. Please consider a different version
```
https://travis-ci.org/softvar/json2html/jobs/583374664

Apparently there are some issues with Ubuntu and Python 2.6 in Travis, Python 2.6 will require the use of `dist: trusty` (which I believe is itself EOLed).

However, do we still need/want to support Python 2.6? it was EOLed in 2013.

**Comment by hugovk** [comment]
I think it's time. Many project are now considering when to drop Python 2.7 (EOL on 2020-01-01), and many already have done.

It's also little used. Here's the pip installs for json2html from PyPI for August 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.7 |  32.54% |    12,014 |
|      2.7 |  28.25% |    10,431 |
|      3.6 |  26.78% |     9,889 |
|      3.5 |   8.79% |     3,246 |
| null     |   2.89% |     1,067 |
|      3.4 |   0.67% |       246 |
|      2.6 |   0.07% |        26 |
|      3.8 |   0.00% |         1 |
| Total    |         |    36,920 |

Source: `pip install -U pypistats && pypistats python_minor json2html --last-month`

**Comment by hugovk** [comment]
Please see PR #44.
