### ISSUE TITLE
Useful element Identification

### ISSUE THREAD

**Issue by kyleshrader** [softvar/json2html#5]
What are your thoughts on adding identifiers (name/id) to the elements?

Is it useful to set:
* td or nested table name to the respective key?
* td class to the respective value type?

**Comment by muellermichel** [comment]
My two cents on this: `id` on the `<th>` is afaik expected to be unique, which is not generally true in json2html. `name` on the other hand is [*not* standard html](http://www.w3.org/TR/html401/struct/tables.html#edef-TD) and will break validators. IMO the way to do this in json2html is to add a table class using `table_attributes` and run Javascript code on the generated table to amend it with whatever attributes you'd like to give it. I'd therefore advocate to close this issue.
