### ISSUE TITLE
Is this 1.0 yet?

### ISSUE THREAD

**Issue by kyleshrader** [softvar/json2html#6]
Would you say this is "1.0"? It works great. 0.3 will give the impression it isn't functional.

**Comment by softvar** [comment]
Yea, sorry. Will update it soon.
Actually I'm impatiently looking for some spare time to revamp / update the library to support many other things and to make it work in python 3.x as well as per many requests.

Thanks for reminding me.

**Comment by softvar** [comment]
New code pushed with test cases and minor fixes, stable version `1.0.0` is now live.

**Comment by kyleshrader** [comment]
grats ^_^
