### ISSUE TITLE
Issue for python 2.6.6

### ISSUE THREAD

**Issue by Midgar77** [softvar/json2html#7]
I'm not sure if this is just for python 2.6.6, but I ran into an issue when trying to use json2html.

When running a simple script that uses json2html's convert function, I received the following error:

  File "/usr/lib/python2.6/site-packages/json2html/jsonconv.py", line 50, in convert
    ordered_json = json.loads(self.json_input, object_pairs_hook=ordereddict.OrderedDict)
  File "/usr/lib64/python2.6/json/__init__.py", line 318, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'object_pairs_hook'

So there seems to be an issue with the line ordered_json = json.loads(self.json_input, object_pairs_hook=ordereddict.OrderedDict)

I solved this issue on my machine by installing simplejson, and then changing the use of the json library to the simplejson library.

**Comment by muellermichel** [comment]
maybe simplejson could be used as a fallback option in case json.loads doesn't support the object_pairs_hook argument? I didn't test the following code but maybe something like

   import inspect
   if "object_pairs_hook" in inspect.getargspec(json.loads).args:
      import json
   else:
      import simplejson
   ! ... json.loads call

**Comment by gjhawar** [comment]
Ya. This is an issue. Why do we need ordered_json = json.loads(self.json_input, object_pairs_hook=ordereddict.OrderedDict)
object_pairs_hook in this anyways?

**Comment by Midgar77** [comment]
I created a json2html converter with much simpler code that does the same job, except I did not include object_pairs_hook. My converter produces the same exact output but doesn't need to use object_pairs_hook or OrderedDict whatsoever. Why exactly does the code use object_pairs_hook?

**Comment by softvar** [comment]
@Midgar77  @gjhawar It's long time back I coded this, will surely debug this weekend and let you guys know.

**Comment by muellermichel** [comment]
@Midgar77 : Will you open source your code? I'd be interested in it.

**Comment by softvar** [comment]
Fixed issue for python2.* version in latest version `1.0.0` + tests.
Check it out.
